### ISSUE TITLE
Handling paged results from listUsage API

### ISSUE THREAD

**Issue by nikmartin** [Chatham/node-cloudstack#1]
I'm using your module to build usage reports using the listUsage API, and am hitting a brick wall. The listUsage function returns a set of records that is paged.  That is, if the result set of records is > pagesize, it returns page 1 of records that is pagesize long. As long as the record count equals pagesize, I need to recursively call the function.  Do you know of a way to accomplish this in the callback of your exec function?  I'm not having any luck because of the asynchronous nature of node/javascript.

**Comment by timsavery** [comment]
We can figure this out :) 

Check out some code I have used accessing the Geekli.st API to use their paged API (https://github.com/NodePhilly/gklst-cards-scroll/blob/master/geeklist.js) ... does this provide any guidance? It basically requires calling back into the API as long as the condition you mentioned (records is > pagesize) is true. If you post a code sample you are using I can dig in and check it out myself and figure it out.

**Comment by nikmartin** [comment]
I think I might can do what I need with the async.whilst function.  Maybe.  Let me undo the terrible Idea I had right at 5 o'clock, and I'll post what I'm trying to do.

**Comment by timsavery** [comment]
No problem. I'll be glad to help if you want/need it. Just let me know. Good luck!

**Comment by nikmartin** [comment]
I think I got it put back together: https://gist.github.com/73d86c589643ff38dd71 
the unindented comments are where my troubles are.

**Comment by timsavery** [comment]
Give this a shot and let me know how you make out: https://gist.github.com/7a882e08b62690cb4a15

You have to fill in the blanks :) I have not tested the code against a CloudStack instance. Should be close though.

**Comment by nikmartin** [comment]
That worked almost perfectly. I have a few more CS async calls to make, so I may end up using the serialize function in async to do the remote queries. Thanks!

**Comment by timsavery** [comment]
No problem! Glad you got it working. Let me know if you need anything else.
